---
- name: Installer et configurer Apache sur les serveurs Debian
  hosts: all
  become: yes

  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present

    - name: S'assurer que le service Apache est démarré et activé
      service:
        name: apache2
        state: started
        enabled: yes
